eno = int(input('Enter Employee NO:'))
ename = input("Enter your name:")
esal = float(input('Enter Employee Salary:')
eadd = input('Enter employee address:')
married = bool(input("Employee married[True/False]:"))
print('Employee Information')
print("Employee No:",eno)
print("Employee Name:",ename)
print("Employee Salary:",esal)
print("Employee Address:",eadd)
print("Employee Married?",married)
